// Generated by CIRCT firtool-1.62.0
module Gpr(
  input         clock,
  input  [2:0]  io_b_read_0_addr,
  output [31:0] io_b_read_0_data,
  input  [2:0]  io_b_read_1_addr,
  output [31:0] io_b_read_1_data,
  input         io_b_write_en,
  input  [2:0]  io_b_write_addr,
  input  [31:0] io_b_write_data
);

  reg  [31:0]      r_gpr_0;
  reg  [31:0]      r_gpr_1;
  reg  [31:0]      r_gpr_2;
  reg  [31:0]      r_gpr_3;
  reg  [31:0]      r_gpr_4;
  reg  [31:0]      r_gpr_5;
  reg  [31:0]      r_gpr_6;
  reg  [31:0]      r_gpr_7;
  wire [7:0][31:0] _GEN =
    {{r_gpr_7},
     {r_gpr_6},
     {r_gpr_5},
     {r_gpr_4},
     {r_gpr_3},
     {r_gpr_2},
     {r_gpr_1},
     {r_gpr_0}};
  always @(posedge clock) begin
    r_gpr_0 <= 32'h0;
    if (io_b_write_en & io_b_write_addr == 3'h1)
      r_gpr_1 <= io_b_write_data;
    if (io_b_write_en & io_b_write_addr == 3'h2)
      r_gpr_2 <= io_b_write_data;
    if (io_b_write_en & io_b_write_addr == 3'h3)
      r_gpr_3 <= io_b_write_data;
    if (io_b_write_en & io_b_write_addr == 3'h4)
      r_gpr_4 <= io_b_write_data;
    if (io_b_write_en & io_b_write_addr == 3'h5)
      r_gpr_5 <= io_b_write_data;
    if (io_b_write_en & io_b_write_addr == 3'h6)
      r_gpr_6 <= io_b_write_data;
    if (io_b_write_en & (&io_b_write_addr))
      r_gpr_7 <= io_b_write_data;
  end // always @(posedge)
  assign io_b_read_0_data = (|io_b_read_0_addr) ? _GEN[io_b_read_0_addr] : 32'h0;
  assign io_b_read_1_data = (|io_b_read_1_addr) ? _GEN[io_b_read_1_addr] : 32'h0;
endmodule

